spring.application.name=code-school

spring.datasource.url=jdbc:sqlite:C:/dev/chinook.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.show-sql=true